
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: localhost
  database: challenge_dev
  user: postgres
  password: dev
  adapter: postgresql

development:
  <<: *default
test:
  <<: *default
  database: challenge_dev
